---
# -------------------------------------------------------------------------------------------------
#
#     Copyright © Genpact 2018. All Rights Reserved.
#     Ltd trading as G in NYSE - Registered in US.
#     Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.
#
# -------------------------------------------------------------------------------------------------
## author = 'Sandeep Kumar (Genpact Limited)'
## ver = '1.0.0'
## date = 22-Feb-2019
# -------------------------------------------------------------------------------------------------
## modified_by = 'Sandeep Kumar (Genpact Limited)'
## ver = '1.0.1'
## changes = "modified environments and removed CloudWatch schedule"
## date = 23-Apr-2019
# -------------------------------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function for creating DB Snapshots

Parameters:
  AccountName:
      Description: AWS Account Name
      Default: pfizer
      Type: String
  PrimaryRegion:
      Type: String
      Default: us-east-1
      Description: Region where you want to create the Lambda function
  EnvType:
      Description: Environment Type
      Default: dev
      Type: String
      AllowedValues: [ dev, sit, ml, ut, pt ]
      ConstraintDescription: Select the Environment for Creation.
# Pre-requisite for Lambda function to create an IAM role
# which will have access on CloudWatch logs, KMS and RDS service
  ExecutionRole:
      Description: Role for Lambda function
      Default: lambda-db-dr-execution
      Type: String
  LambdaS3Bucket:
      Description: S3 Bucket for Lambda Function
      Default: "pvai-devops-lambda-functions"
      Type: String
  MemorySize:
      Description: Memory Size for Lambda function
      Default: 128
      Type: String
  TimeOut:
      Description: TimeOut for Lambda function (in seconds)
      Default: 300
      Type: String
  PythonPackage:
      Description: Python function as a package with all dependencies
      Default: "Orcl_DB_Snapshots.zip"
      Type: String
  DatabaseID:
      Description: Database Identifier
      Default: "dbdev"
      Type: String
Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
          S3Bucket: !Ref LambdaS3Bucket
          S3Key: !Ref PythonPackage
        Description: "create db snapshots"
        Environment:
          Variables:
            PRIMARY_REGION: !Ref PrimaryRegion
            DB_ID: !Ref DatabaseID
        FunctionName: !Sub "${AccountName}-${EnvType}-create-db-snapshots"
        Handler: "Orcl_DB_Snapshots.lambda_handler"
        MemorySize: !Ref MemorySize
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ExecutionRole}"
        Runtime: "python2.7"
        Timeout: !Ref TimeOut
        Tags:
          - Key: Name
            Value: !Sub "${EnvType}-DB-Snapshots"
          - Key: Account
            Value: !Ref AccountName
          - Key: Environment
            Value: !Ref EnvType

Outputs:
  LambdaArn:
    Value: !GetAtt "LambdaFunction.Arn"