#------------------------------------------------------------------------------------#
## Copyright © Genpact 2018. All Rights Reserved.                                   ##
## Ltd trading as G in NYSE - Registered in US.                                     ##
## Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.  ##
#------------------------------------------------------------------------------------#
## Author = 'Vivek Trivedi (Genpact Limited)'                                       ##
## Version = '1.0.0'                                                                ##
## Date = 6-Apr-2018                                                                ##
#------------------------------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description: OPERATIONS VPC Subnet RouteTable Association
Parameters:
    Region: 
        Description: AWS Region
        Default: N-Virginia(us-east-1)
        Type: String
        AllowedValues: 
           - N-Virginia(us-east-1)
           - Ireland(eu-west-1)
        ConstraintDescription: Select the Region for creation.
Conditions: 
  CreateCondition-A: !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition-B: !Equals [ !Ref Region, Ireland(eu-west-1) ]
Resources:
  routetableAssociation11aA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-A
    Properties:
        SubnetId: !ImportValue subnet11aA
        RouteTableId: !ImportValue vpc1rt1aA  
  
  routetableAssociation12aA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-A
    Properties:
        SubnetId: !ImportValue subnet12aA        
        RouteTableId: !ImportValue vpc1rt1aA 
        
  routetableAssociation11aB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-B
    Properties:
        SubnetId: !ImportValue subnet11aB        
        RouteTableId: !ImportValue vpc1rt1aB  
  
  routetableAssociation12aB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-B
    Properties:
        SubnetId: !ImportValue subnet12aB         
        RouteTableId: !ImportValue vpc1rt1aB

  routetableAssociation13bA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-A
    Properties:
        SubnetId: !ImportValue subnet13bA         
        RouteTableId: !ImportValue vpc1rt2bA

  routetableAssociation14bA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-A
    Properties:
        SubnetId: !ImportValue subnet14bA        
        RouteTableId: !ImportValue vpc1rt2bA

  routetableAssociation13bB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-B
    Properties:
        SubnetId: !ImportValue subnet13bB        
        RouteTableId: !ImportValue vpc1rt2bB

  routetableAssociation14bB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateCondition-B
    Properties:
        SubnetId: !ImportValue subnet14bB        
        RouteTableId: !ImportValue vpc1rt2bB        