---
# -------------------------------------------------------------------------------------------------
#
#     Copyright © Genpact 2018. All Rights Reserved.
#     Ltd trading as G in NYSE - Registered in US.
#     Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.
#
# -------------------------------------------------------------------------------------------------
## author = 'Sandeep Kumar (Genpact Limited)'
## ver = '1.0.0'
## date = 22-Feb-2019
# -------------------------------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function for deleting DB Snapshots

Parameters:
  AccountName:
      Description: AWS Account Name
      Default: verification
      Type: String
  Region:
      Type: String
      Default: us-east-1
      Description: Region where you want to create the Lambda function
  EnvType:
      Description: Environment Type
      Default: prod
      Type: String
      AllowedValues: [ val, prod ]
      ConstraintDescription: Select the Environment for Creation.
# Pre-requisite for Lambda function to create an IAM role
# which will have access on CloudWatch logs, KMS and RDS service
  ExecutionRole:
      Description: Role for Lambda function
      Default: lambda-db-dr-execution
      Type: String
  LambdaS3Bucket:
      Description: S3 Bucket for Lambda Function
      Default: "pvai-devops-lambda-functions"
      Type: String
  MemorySize:
      Description: Memory Size for Lambda function
      Default: 128
      Type: String
  TimeOut:
      Description: TimeOut for Lambda function (in seconds)
      Default: 300
      Type: String
  ScheduleExpression:
      Description: Scheduled Time for Lambda Function Execution
      Default: "cron(0 23 * * ? *)"
      Type: String
  PythonPackage:
      Description: Python function as a package with all dependencies
      Default: "Orcl_Delete_Snapshots.zip"
      Type: String
  DatabaseID:
      Description: Database Identifier
      Default: "dbprod"
      Type: String
  RetentionDays:
      Description: Retention Days for Manual Snapshots
      Default: "1"
      Type: String
Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
          S3Bucket: !Ref LambdaS3Bucket
          S3Key: !Ref PythonPackage
        Description: "delete db snapshots created by lambda function"
        Environment:
          Variables:
            REGION: !Ref Region
            DB_ID: !Ref DatabaseID
            RETENTION_DAYS: !Ref RetentionDays            
        FunctionName: !Sub "${AccountName}-${EnvType}-delete-db-snapshots"
        Handler: "Orcl_Delete_Snapshots.lambda_handler"
        MemorySize: !Ref MemorySize
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ExecutionRole}"
        Runtime: "python2.7"
        Timeout: !Ref TimeOut
        Tags:
          - Key: Name
            Value: !Sub "${EnvType}-Delete-DB-Snapshots"
          - Key: Account
            Value: !Ref AccountName
          - Key: Environment
            Value: !Ref EnvType
            
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub "Schedule Lambda function to delete db snapshots"
      Name: !Sub "${EnvType}-Delete-Snapshots"
      # runs every day at defined time
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"

Outputs:
  LambdaArn:
    Value: !GetAtt "LambdaFunction.Arn"
  RuleArn:
    Value: !GetAtt "ScheduledRule.Arn"