# -------------------------------------------------------------------------------------------------
#
#     Copyright © Genpact 2018. All Rights Reserved.
#     Ltd trading as G in NYSE - Registered in US.
#     Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.
#
# -------------------------------------------------------------------------------------------------
## author = 'Muqaddis Hussain (Genpact Limited)'
## ver = '1.0.0'
## date = 08-April-2019
## created = "segregated WAR File of application",
# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------
## modified_by = 'Sandeep Kumar (Genpact Limited)'
## ver = '1.0.1'
## changes = "Base AMI to be used instead of encrypted one and encryption on the fly for the volumes"
##           "Addition of Server.xml and filebeat.yml"
## date = 18-Jul-2019
# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------
## modified_by = 'Sandeep Kumar (Genpact Limited)'
## ver = '1.0.2'
## changes = "JKS files handled dynamically"
## date = 22-Jul-2019
# -------------------------------------------------------------------------------------------------

Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: 2010-09-09
Description: Creates Core-Batch LB, LC and ASG in VPC2 for the environment
Parameters:
    Prefix:
        Description: Prefix Name
        Default: pvai
        Type: String
    Account:
        Description: Account Name
        Default: verification
        Type: String
    Region:
        Description: AWS Region
        Default: Primary
        Type: String
        AllowedValues: 
           - Primary
           - Secondary
        ConstraintDescription: Select the Region for creation.     
    EnvType: 
        Description: Environment Type
        Default: prod
        Type: String
        AllowedValues: 
           - dev
           - ml
           - sit
           - val
           - prod
           - ut
           - pt
        ConstraintDescription: Select the Environment for Creation.
    AMI:
        Description: AMI for EC2 Instance
        Default: ami-0e26966840a3e78b4
        Type: AWS::EC2::Image::Id        
    InstanceType:
        Description: Instance Type
        Default: m5.large
        Type: String
        AllowedValues: [ t2.medium, t2.xlarge, m4.large, m4.xlarge, m5.large, m5.xlarge ]
        ConstraintDescription: Select the Instance Type for EC2.
    RootVolumeSize:
        Description: Root volume size.
        Type: String
        Default: "100"
    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
        Type: 'AWS::EC2::KeyPair::KeyName'
        Default: pvai-verification-prod
    EC2KmsKeyId:
        Description: KMS Key for EC2 Volume Encryption
        Default: "591fd75e-5b4f-4208-8b0d-199eadfa55f9"
        Type: String
    InstanceProfile:
        Description: Instance Role
        Default: EC2-S3-AccessRole
        Type: String
    DesiredCapacity:
       Description: EC2 Instance Desired for Application
       Type: Number
       Default: 1
       ConstraintDescription: 'Must be in the range [1-10]'
       MinValue: 1
       MaxValue: 10
    CIDR:
       Description: IP range for the security group
       Type: String
       Default: "10.0.0.0/8"
    S3Bucket:
       Description: S3 Bucket for War file
       Type: String
       Default: "pvai-verification-deployment"
    # Major and Minor releases and Artifacts path
    MajorRelease:
      Description: Major version of the Product
      Type: String
      Default: "intake-1.0"
    MinorRelease:
      Description: Minor version of the application
      Type: String
      Default: "102C"
    BuildNumber:
      Description: BuildNumber of Core-App application
      Type: String
      Default: "285"
    PackagePath:
      Description: Path for the war files (after Application folder)
      Type: String
      Default: "packages"
    ConfigFilesPath:
      Description: Path for the config files (after environment folder)
      Type: String
      Default: "config"
    JKSFilesPath:
      Description: Path for the jks files (after environment folder)
      Type: String
      Default: "crt"
    LBDeregistrationDelay:
       Description: The maximum time, in seconds, to keep existing connections open before deregistering the instances
       Type: Number
       Default: 60
       ConstraintDescription: 'Must be in the range [0-600]'
       MinValue: 0
       MaxValue: 600
    StickinessDuration:
       Description: The time period, in seconds, after which the cookie should be considered stale
       Type: Number
       Default: 1800
       ConstraintDescription: 'Must be in the range [0-3600]'
       MinValue: 0
       MaxValue: 3600
    IdleTimeout:
       Description: The time (in seconds) that a connection to the load balancer can remain idle
       Type: Number
       Default: 1800
       ConstraintDescription: 'Must be in the range [0-3600]'
       MinValue: 0
       MaxValue: 3600
    HostedZoneResource:
       Description: Private DNS
       Type: String
       Default: "local."
    CertID:
       Description: Certificate Identifier to be used for ELB
       Type: String
       Default: "1108d510-800f-4bd0-8409-0272a81d7f73"
    App:
       Description: Application Name
       Type: String
       Default: "bat"
    AppPort:
       Description: Port being used to hit the Application
       Type: String
       Default: 8080
       AllowedPattern: ^[0-9/]*$
Conditions: 
  # Create condition based on the Environment selected;
  # To fetch the VPC and Subnet values based on the condition
  GetDevNetworkValues: !And
       - !Equals [ !Ref EnvType, "dev" ]
       - !Equals [ !Ref Region, Primary ]
  GetMLNetworkValues: !And
       - !Equals [ !Ref EnvType, "ml"]
       - !Equals [ !Ref Region, Primary ]
  GetPTNetworkValues: !And
       - !Equals [ !Ref EnvType, "pt"]
       - !Equals [ !Ref Region, Primary ]
  GetUTNetworkValues: !And
       - !Equals [ !Ref EnvType, "ut"]
       - !Equals [ !Ref Region, Primary ]
  GetSITNetworkValues: !And
       - !Equals [ !Ref EnvType, "sit"]
       - !Equals [ !Ref Region, Primary ]
  GetValNetworkValues: !And
       - !Equals [ !Ref EnvType, "val"]
       - !Equals [ !Ref Region, Primary ]
  GetProdNetworkValues: !And
       - !Equals [ !Ref EnvType, "prod"]
       - !Equals [ !Ref Region, Primary ]
  GetProdNetworkValuesSecondary: !And
       - !Equals [ !Ref EnvType, "prod"]
       - !Equals [ !Ref Region, Secondary ]
  GetValNetworkValuesSecondary: !And
       - !Equals [ !Ref EnvType, "val"]
       - !Equals [ !Ref Region, Secondary ]
Resources:
  sg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub ${Prefix}-${EnvType}-${App}-vpc2  
      GroupDescription: !Sub "Security Group for Core-Batch application for ${EnvType} environment"
      VpcId: !If [GetValNetworkValues, !ImportValue vpc20A, !If [GetProdNetworkValues, !ImportValue vpc20A, !If [GetDevNetworkValues, !ImportValue vpc21A, !If [GetMLNetworkValues, !ImportValue vpc21A, !If [GetPTNetworkValues, !ImportValue vpc24A, !If [GetUTNetworkValues, !ImportValue vpc23A, !If [GetSITNetworkValues, !ImportValue vpc22A, !If [GetProdNetworkValuesSecondary,!ImportValue vpc20B, !If [GetValNetworkValuesSecondary, !ImportValue vpc20B, ""]]]]]]]]]
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-${EnvType}-${App}-vpc2

  sgingress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sg
      IpProtocol: '-1'
      CidrIp: !Ref CIDR 
  
  launchconfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          # Just for testing purpose to debug if file is created or not
          files:
            /tmp/test.txt:
              content: Hello Core-Batch World!
              mode: '000755'
              owner: root
              group: root
          commands:
            # get configuration files and paste it to the proper location;
            #get ROOT.war from s3 bucket, move it to proper location and
            1-downloadfilesandpackages:
              command: !Sub "aws s3 cp s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${EnvType}/${ConfigFilesPath}/config.properties /usr/local/tomcat/PVAI/lib/ && aws s3 cp s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${EnvType}/${ConfigFilesPath}/context.xml /usr/local/tomcat/PVAI/conf/ && aws s3 cp s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${EnvType}/${ConfigFilesPath}/server.xml /usr/local/tomcat/PVAI/conf/ && aws s3 cp s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${EnvType}/${ConfigFilesPath}/mailTemplate.vm /usr/local/tomcat/PVAI/lib/ && aws s3 cp s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${PackagePath}/PVAIBatch.war /usr/local/tomcat/PVAI/webapps/"
              cwd: "~"
              ignoreErrors: "false" 
           # change permissions and ownerships
            2-modifypermsandownership:
              command: !Sub "chown -R ec2-user:ec2-user /usr/local/tomcat/PVAI/ && chmod 640 /usr/local/tomcat/PVAI/lib/config.properties && chmod 600 /usr/local/tomcat/PVAI/conf/context.xml && chmod 664 /usr/local/tomcat/PVAI/lib/mailTemplate.vm && chmod 600 /usr/local/tomcat/PVAI/conf/server.xml"
              cwd: "~"
              ignoreErrors: "false"
            # download filebeat yml file
            3-downloadfilebeatyml:
              command: !Sub "aws s3 cp s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${EnvType}/filebeat.yml /etc/filebeat/"
              cwd: "~"
              ignoreErrors: "false"
            # download jks files for integrating with client systems
            4-downloadjksfiles:
              command: !Sub "aws s3 sync s3://${S3Bucket}/${MajorRelease}/${MinorRelease}/${BuildNumber}/${App}/${EnvType}/${JKSFilesPath}/ /usr/local/tomcat/PVAI/lib/" && chmod 600 /usr/local/tomcat/PVAI/lib/*.jks
              cwd: "~"
              ignoreErrors: "true"
            # stop/start the tomcat service
            5-restartservices:
              command: !Sub "service tomcat stop && sleep 5 && service tomcat start && service filebeat restart"
              cwd: "~"
              ignoreErrors: "false"
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      EbsOptimized: "true"
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      InstanceMonitoring: 'true'
      AssociatePublicIpAddress: 'false'
      SecurityGroups:
        - !Ref sg 
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: !Ref RootVolumeSize
            VolumeType: "gp2"
            Encrypted: "true"
            #KmsKeyId: !Ref EC2KmsKeyId

      # User Data commands to be run during Initialization of Server
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource launchconfig --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource asgroup --region ${AWS::Region}
            
  asgroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      Cooldown: '300'
      DesiredCapacity: !Ref DesiredCapacity
      HealthCheckGracePeriod: '300'
      HealthCheckType: ELB
      MaxSize: '4'
      MinSize: '1'
      VPCZoneIdentifier:
        - !If [GetValNetworkValues, !ImportValue subnet23b0A, !If [GetProdNetworkValues, !ImportValue subnet24b0A, !If [GetDevNetworkValues, !ImportValue subnet23b1A, !If [GetMLNetworkValues, !ImportValue subnet24b1A, !If [GetPTNetworkValues, !ImportValue subnet23b4A, !If [GetUTNetworkValues, !ImportValue subnet23b3A, !If [GetSITNetworkValues, !ImportValue subnet23b2A, !If [GetProdNetworkValuesSecondary,!ImportValue subnet24b0B, !If [GetValNetworkValuesSecondary, !ImportValue subnet23b0B, ""]]]]]]]]]
        - !If [GetValNetworkValues, !ImportValue subnet25b0A, !If [GetProdNetworkValues, !ImportValue subnet26b0A, !If [GetDevNetworkValues, !ImportValue subnet25b1A, !If [GetMLNetworkValues, !ImportValue subnet26b1A, !If [GetPTNetworkValues, !ImportValue subnet24b4A, !If [GetUTNetworkValues, !ImportValue subnet24b3A, !If [GetSITNetworkValues, !ImportValue subnet24b2A, !If [GetProdNetworkValuesSecondary,!ImportValue subnet26b0B, !If [GetValNetworkValuesSecondary, !ImportValue subnet25b0B, ""]]]]]]]]]
      LaunchConfigurationName: !Ref launchconfig
      LoadBalancerNames:
        - !Ref ClassicLoadBalancer         
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-${EnvType}-${App}"
          PropagateAtLaunch: true
        - Key: Project
          Value: !Ref App
          PropagateAtLaunch: true
        - Key: Environment
          Value: !Ref EnvType
          PropagateAtLaunch: true
        - Key: Scheduled
          Value: "no"
          PropagateAtLaunch: true
      TerminationPolicies:
        - Default
    DependsOn:
        - ClassicLoadBalancer      
     #Creation policy for resource creation and deployment
    CreationPolicy:
      AutoScalingCreationPolicy:
        MinSuccessfulInstancesPercent: 100
      ResourceSignal:
        Count: '1'
        Timeout: PT15M
    #Update policy for deploying new version
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: 'true'
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '2'
        PauseTime: PT3M
        WaitOnResourceSignals: 'true'

  # Classic LoadBalancer for Core-Batch application
  ClassicLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName: !Sub ${Prefix}-${EnvType}-${App}-clb
      Scheme: internal
      CrossZone: True
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: !Ref LBDeregistrationDelay
      ConnectionSettings:
        IdleTimeout: !Ref IdleTimeout
      SecurityGroups: 
        - !Ref sg
      # fetch ELB Subnet1 and ELB Subnet2 values
      Subnets:
        - !If [GetValNetworkValues, !ImportValue subnet23b0A, !If [GetProdNetworkValues, !ImportValue subnet24b0A, !If [GetDevNetworkValues, !ImportValue subnet23b1A, !If [GetMLNetworkValues, !ImportValue subnet24b1A, !If [GetPTNetworkValues, !ImportValue subnet23b4A, !If [GetUTNetworkValues, !ImportValue subnet23b3A, !If [GetSITNetworkValues, !ImportValue subnet23b2A, !If [GetProdNetworkValuesSecondary,!ImportValue subnet24b0B, !If [GetValNetworkValuesSecondary, !ImportValue subnet23b0B, ""]]]]]]]]]
        - !If [GetValNetworkValues, !ImportValue subnet25b0A, !If [GetProdNetworkValues, !ImportValue subnet26b0A, !If [GetDevNetworkValues, !ImportValue subnet25b1A, !If [GetMLNetworkValues, !ImportValue subnet26b1A, !If [GetPTNetworkValues, !ImportValue subnet24b4A, !If [GetUTNetworkValues, !ImportValue subnet24b3A, !If [GetSITNetworkValues, !ImportValue subnet24b2A, !If [GetProdNetworkValuesSecondary,!ImportValue subnet26b0B, !If [GetValNetworkValuesSecondary, !ImportValue subnet25b0B, ""]]]]]]]]]
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-${EnvType}-${App}
        - Key: Project
          Value: !Ref App
        - Key: Environment
          Value: !Ref EnvType
      Listeners:
      - LoadBalancerPort: '443'
        InstancePort:
          Ref: AppPort
        Protocol: HTTPS
        SSLCertificateId: !Sub "arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${CertID}"
        PolicyNames:
          - "LBCoreAppPolicy"
      LBCookieStickinessPolicy:
        -
          CookieExpirationPeriod: !Ref StickinessDuration
          PolicyName: "LBCoreAppPolicy"
      HealthCheck:
        Target:
          Fn::Join:
          - ''
          - - 'HTTP:'
            - Ref: AppPort
            - "/login"
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'

  # Create alarm to identify any unhealthy host under Core-Batch Classic LoadBalancer
  UnhealthyHostAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
         AlarmName: !Sub ${Prefix}-${EnvType}-${App}-alarm
         AlarmDescription: Unhealthy host under Core-Batch CLB
         Namespace: AWS/ELB
         Dimensions:
          - Name: LoadBalancerName
            Value: !Sub ${Prefix}-${EnvType}-${App}-clb
         MetricName: UnHealthyHostCount
         ComparisonOperator: GreaterThanThreshold
         Statistic: Minimum
         Period: 60
         EvaluationPeriods: 1
         Threshold: 0

  # Creating DNS record for Core-Batch CLB
  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneResource
      Comment: Zone apex alias targeted to Elastic LoadBalancer.
      RecordSets:
      - Name: !Sub "${Prefix}-${EnvType}-${App}-clb.${HostedZoneResource}"
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt ClassicLoadBalancer.CanonicalHostedZoneNameID
          DNSName: !GetAtt ClassicLoadBalancer.DNSName

Outputs:
  asg4app:
    Description: The value of ASG for the application
    Value: !Ref asgroup
    Export:
      Name: asg4batch
  lc4asg:
    Description: The value of Launch Configuration for ASG
    Value: !Ref launchconfig
    Export:
      Name: lc4asgbatch