#------------------------------------------------------------------------------------#
## Copyright © Genpact 2018. All Rights Reserved.                                   ##
## Ltd trading as G in NYSE - Registered in US.                                     ##
## Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.  ##
#------------------------------------------------------------------------------------#
## Author = 'Vivek Trivedi (Genpact Limited)'                                       ##
## Version = '1.0.0'                                                                ##
## Date = 6-Apr-2018                                                                ##
#------------------------------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description: CORE VPC - RouteTables 
Parameters:
    Region: 
        Description: AWS Region
        Default: N-Virginia(us-east-1)
        Type: String
        AllowedValues: 
           - N-Virginia(us-east-1)
           - Ireland(eu-west-1)
        ConstraintDescription: Select the Region for creation.
    EnvType: 
        Description: Environment Type
        Default: DEV/ML
        Type: String
        AllowedValues: 
           - DEV/ML
           - SIT
           - VAL/PROD
           - UserTraining
           - PerformanceTesting
        ConstraintDescription: Select the Environment for Creation.
Conditions: 
  CreateCondition1A: !And
        - !Equals [ !Ref EnvType, DEV/ML ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition2A: !And
        - !Equals [ !Ref EnvType, SIT ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition0A: !And
        - !Equals [ !Ref EnvType, VAL/PROD ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition0B: !And
        - !Equals [ !Ref Region, Ireland(eu-west-1) ]
        - !Equals [ !Ref EnvType, VAL/PROD ]
  CreateCondition3A: !And
        - !Equals [ !Ref EnvType, UserTraining ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition4A: !And
        - !Equals [ !Ref EnvType, PerformanceTesting ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
Resources:        
  vpc2rt1a1A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition1A
    Properties:
      VpcId: !ImportValue vpc21A
      Tags:
        - Key: Name
          Value: vpc2rt1a1A
  vpc2rt2b1A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition1A
    Properties:
      VpcId: !ImportValue vpc21A
      Tags:
        - Key: Name
          Value: vpc2rt2b1A
  vpc2rt1a2A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition2A
    Properties:
      VpcId: !ImportValue vpc22A
      Tags:
        - Key: Name
          Value: vpc2rt1a2A
  vpc2rt2b2A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition2A
    Properties:
      VpcId: !ImportValue vpc22A
      Tags:
        - Key: Name
          Value: vpc2rt2b2A
  vpc2rt1a0A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0A
    Properties:
      VpcId: !ImportValue vpc20A
      Tags:
        - Key: Name
          Value: vpc2rt1a0A
  vpc2rt2b0A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0A
    Properties:
      VpcId: !ImportValue vpc20A
      Tags:
        - Key: Name
          Value: vpc2rt2b0A
  vpc2rt1a0B:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0B
    Properties:
      VpcId: !ImportValue vpc20B
      Tags:
        - Key: Name
          Value: vpc2rt1a0B
  vpc2rt2b0B:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0B
    Properties:
      VpcId: !ImportValue vpc20B
      Tags:
        - Key: Name
          Value: vpc2rt2b0B
  vpc2rt1a3A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition3A
    Properties:
      VpcId: !ImportValue vpc23A
      Tags:
        - Key: Name
          Value: vpc2rt1a3A
  vpc2rt2b3A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition3A
    Properties:
      VpcId: !ImportValue vpc23A
      Tags:
        - Key: Name
          Value: vpc2rt2b3A
  vpc2rt1a4A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition4A
    Properties:
      VpcId: !ImportValue vpc24A
      Tags:
        - Key: Name
          Value: vpc2rt1a4A
  vpc2rt2b4A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition4A
    Properties:
      VpcId: !ImportValue vpc24A
      Tags:
        - Key: Name
          Value: vpc2rt2b4A          
  vpc3rt1a1A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition1A
    Properties:
      VpcId: !ImportValue vpc31A
      Tags:
        - Key: Name
          Value: vpc3rt1a1A
  vpc3rt2b1A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition1A
    Properties:
      VpcId: !ImportValue vpc31A
      Tags:
        - Key: Name
          Value: vpc3rt2b1A
  vpc3rt1a2A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition2A
    Properties:
      VpcId: !ImportValue vpc32A
      Tags:
        - Key: Name
          Value: vpc3rt1a2A
  vpc3rt2b2A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition2A
    Properties:
      VpcId: !ImportValue vpc32A
      Tags:
        - Key: Name
          Value: vpc3rt2b2A
  vpc3rt1a0A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0A
    Properties:
      VpcId: !ImportValue vpc30A
      Tags:
        - Key: Name
          Value: vpc3rt1a0A
  vpc3rt2b0A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0A
    Properties:
      VpcId: !ImportValue vpc30A
      Tags:
        - Key: Name
          Value: vpc3rt2b0A
  vpc3rt1a0B:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0B
    Properties:
      VpcId: !ImportValue vpc30B
      Tags:
        - Key: Name
          Value: vpc3rt1a0B
  vpc3rt2b0B:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition0B
    Properties:
      VpcId: !ImportValue vpc30B
      Tags:
        - Key: Name
          Value: vpc3rt2b0B
  vpc3rt1a3A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition3A
    Properties:
      VpcId: !ImportValue vpc33A
      Tags:
        - Key: Name
          Value: vpc3rt1a3A
  vpc3rt2b3A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition3A
    Properties:
      VpcId: !ImportValue vpc33A
      Tags:
        - Key: Name
          Value: vpc3rt2b3A
  vpc3rt1a4A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition4A
    Properties:
      VpcId: !ImportValue vpc34A
      Tags:
        - Key: Name
          Value: vpc3rt1a4A
  vpc3rt2b4A:
    Type: 'AWS::EC2::RouteTable'
    Condition: CreateCondition4A
    Properties:
      VpcId: !ImportValue vpc34A
      Tags:
        - Key: Name
          Value: vpc3rt2b4A
Outputs:
  vpc2rt1a1A:
    Description: The value for VPC-2 RouteTable-1 Public Routes for DEV-ML Environment for Virginia
    Condition: CreateCondition1A
    Value: !Ref vpc2rt1a1A
    Export:
      Name: vpc2rt1a1A
  vpc2rt2b1A:
    Description: The value for VPC-2 RouteTable-2 Private Routes for  DEV-ML Environment for Virginia
    Condition: CreateCondition1A
    Value: !Ref vpc2rt2b1A
    Export:
      Name: vpc2rt2b1A
  vpc2rt1a2A:
    Description: The value for VPC-2 RouteTable-1 Public Routes for SIT Environment for Virginia
    Condition: CreateCondition2A
    Value: !Ref vpc2rt1a2A
    Export:
      Name: vpc2rt1a2A
  vpc2rt2b2A:
    Description: The value for VPC-2 RouteTable-2 Private Routes for SIT Environment for Virginia
    Condition: CreateCondition2A
    Value: !Ref vpc2rt2b2A
    Export:
      Name: vpc2rt2b2A
  vpc2rt1a0A:
    Description: The value for VPC-2 RouteTable-1 Public Routes for  VAL-PROD Environment for Virginia
    Condition: CreateCondition0A
    Value: !Ref vpc2rt1a0A
    Export:
      Name: vpc2rt1a0A 
  vpc2rt2b0A:
    Description: The value for VPC-2 RouteTable-2 Private Routes for VAL-PROD Environment for Virginia
    Condition: CreateCondition0A
    Value: !Ref vpc2rt2b0A
    Export:
      Name: vpc2rt2b0A
  vpc2rt1a0B:
    Description: The value for VPC-2 RouteTable-1 Public Routes for VAL-PROD Environment for Ireland
    Condition: CreateCondition0B
    Value: !Ref vpc2rt1a0B
    Export:
      Name: vpc2rt1a0B
  vpc2rt2b0B:
    Description: The value for VPC-2 RouteTable-2 Private Routes for VAL-PROD Environment for Ireland
    Condition: CreateCondition0B
    Value: !Ref vpc2rt2b0B
    Export:
      Name: vpc2rt2b0B
  vpc2rt1a3A:
    Description: The value for VPC-2 RouteTable-1 Public Routes for UserTraining Environment for Virginia
    Condition: CreateCondition3A
    Value: !Ref vpc2rt1a3A 
    Export:
      Name: vpc2rt1a3A
  vpc2rt2b3A:
    Description: The value for VPC-2 RouteTable-2 Private Routes for UserTraining Environment for Virginia
    Condition: CreateCondition3A
    Value: !Ref vpc2rt2b3A 
    Export:
      Name: vpc2rt2b3A
  vpc2rt1a4A:
    Description: The value for VPC-2 RouteTable-1 Public Routes for  PerformanceTesting Environment for Virginia
    Condition: CreateCondition4A
    Value: !Ref vpc2rt1a4A
    Export:
      Name: vpc2rt1a4A
  vpc2rt2b4A:
    Description: The value for VPC-2 RouteTable-2 Private Routes for PerformanceTesting Environment for Virginia
    Condition: CreateCondition4A
    Value: !Ref vpc2rt2b4A
    Export:
      Name: vpc2rt2b4A
  vpc3rt1a1A:
    Description: The value for VPC-3 RouteTable-1 Public Routes for DEV-ML Environment for Virginia
    Condition: CreateCondition1A
    Value: !Ref vpc3rt1a1A
    Export:
      Name: vpc3rt1a1A
  vpc3rt2b1A:
    Description: The value for VPC-3 RouteTable-2 Private Routes for DEV-ML Environment for Virginia
    Condition: CreateCondition1A
    Value: !Ref vpc3rt2b1A
    Export:
      Name: vpc3rt2b1A
  vpc3rt1a2A:
    Description: The value for VPC-3 RouteTable-1 Public Routes for SIT Environment for Virginia
    Condition: CreateCondition2A
    Value: !Ref vpc3rt1a2A
    Export:
      Name: vpc3rt1a2A
  vpc3rt2b2A:
    Description: The value for VPC-3 RouteTable-2 Private Routes for SIT Environment for Virginia
    Condition: CreateCondition2A
    Value: !Ref vpc3rt2b2A
    Export:
      Name: vpc3rt2b2A
  vpc3rt1a0A:
    Description: The value for VPC-3 RouteTable-1 Public Routes for VAL-PROD Environment for Virginia
    Condition: CreateCondition0A
    Value: !Ref vpc3rt1a0A 
    Export:
      Name: vpc3rt1a0A
  vpc3rt2b0A:
    Description: The value for VPC-3 RouteTable-2 Private Routes for VAL-PROD Environment for Virginia
    Condition: CreateCondition0A
    Value: !Ref vpc3rt2b0A
    Export:
      Name: vpc3rt2b0A
  vpc3rt1a0B:
    Description: The value for VPC-3 RouteTable-1 Public Routes for VAL-PROD Environment for Ireland
    Condition: CreateCondition0B
    Value: !Ref vpc3rt1a0B
    Export:
      Name: vpc3rt1a0B
  vpc3rt2b0B:
    Description: The value for VPC-3 RouteTable-2 Private Routes for VAL-PROD Environment for Ireland
    Condition: CreateCondition0B
    Value: !Ref vpc3rt2b0B
    Export:
      Name: vpc3rt2b0B
  vpc3rt1a3A:
    Description: The value for VPC-3 RouteTable-1 Public Routes for UserTraining Environment for Virginia
    Condition: CreateCondition3A
    Value: !Ref vpc3rt1a3A
    Export:
      Name: vpc3rt1a3A
  vpc3rt2b3A:
    Description: The value for VPC-3 RouteTable-2 Private Routes for UserTraining Environment for Virginia
    Condition: CreateCondition3A
    Value: !Ref vpc3rt2b3A
    Export:
      Name: vpc3rt2b3A
  vpc3rt1a4A:
    Description: The value for VPC-3 RouteTable-1 Public PerformanceTesting Environment for Virginia
    Condition: CreateCondition4A
    Value: !Ref vpc3rt1a4A
    Export:
      Name: vpc3rt1a4A
  vpc3rt2b4A:
    Description: The value for VPC-3 RouteTable-2 Private Routes for PerformanceTesting Environment for Virginia
    Condition: CreateCondition4A
    Value: !Ref vpc3rt2b4A 
    Export:
      Name: vpc3rt2b4A