#------------------------------------------------------------------------------------#
## Copyright © Genpact 2018. All Rights Reserved.                                   ##
## Ltd trading as G in NYSE - Registered in US.                                     ##
## Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.  ##
#------------------------------------------------------------------------------------#
## Author = 'Vivek Trivedi (Genpact Limited)'                                       ##
## Version = '1.0.0'                                                                ##
## Date = 6-Apr-2018                                                                ##
#------------------------------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description: Operations Public-Subnets
Parameters:
    Region: 
        Description: AWS Region
        Default: N-Virginia(us-east-1)
        Type: String
        AllowedValues: 
           - N-Virginia(us-east-1)
           - Ireland(eu-west-1)
        ConstraintDescription: Select the Region for creation.
Conditions: 
  CreateCondition-A: !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition-B: !Equals [ !Ref Region, Ireland(eu-west-1) ]
Resources:
  subnet11aA:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition-A
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1b
      VpcId: !ImportValue vpc1A
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: subnet-11a-A
  subnet12aA:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition-A
    Properties:
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: us-east-1c
      VpcId: !ImportValue vpc1A
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: subnet-12a-A
  subnet11aB:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition-B
    Properties:
      CidrBlock: 10.1.0.0/24
      AvailabilityZone: eu-west-1b
      VpcId: !ImportValue vpc1B
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: subnet-11a-B
  subnet12aB:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition-B
    Properties:
      CidrBlock: 10.1.4.0/24
      AvailabilityZone: eu-west-1c
      VpcId: !ImportValue vpc1B
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: subnet-12a-B
Outputs:
  subnet11aA:
    Description: The Subnet-ID of the VPC1 Subnet1 PublicSubnet in Virginia. 
    Condition: CreateCondition-A
    Value: !Ref subnet11aA
    Export:
      Name: subnet11aA
  subnet12aA:
    Description: The Subnet-ID of the VPC1 Subnet2 PublicSubnet in Virginia. 
    Condition: CreateCondition-A
    Value: !Ref subnet12aA
    Export:
      Name: subnet12aA  
  subnet11aB:
    Description: The Subnet-ID of the VPC1 Subnet1 PublicSubnet in Ireland. 
    Condition: CreateCondition-B
    Value: !Ref subnet11aB
    Export:
      Name: subnet11aB
  subnet12aB:
    Description: The Subnet-ID of the VPC1 Subnet2 PublicSubnet in Ireland. 
    Condition: CreateCondition-B
    Value: !Ref subnet12aB
    Export:
      Name: subnet12aB