#!/bin/bash
# chkconfig: 2345 99 01
# description: Confluence Server Startup Script

# Confluence Linux service controller script
cd "/usr/local/atlassian/confluence/bin"

case "$1" in
    start)
        ./start-confluence.sh
        ;;
    stop)
        ./stop-confluence.sh
        ;;
    restart)
        ./stop-confluence.sh
        ./start-confluence.sh
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
