#!/bin/bash
# chkconfig: 2345 99 01
# description: JIRA Server

# JIRA Linux service controller script
cd "/usr/local/atlassian/jira/bin"

case "$1" in
    start)
        ./start-jira.sh
        ;;
    stop)
        ./stop-jira.sh
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
