#------------------------------------------------------------------------------------#
##  Copyright © Genpact 2018. All Rights Reserved.                                  ##
##  Ltd trading as G in NYSE - Registered in US.                                    ##
##  Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda. ##
#------------------------------------------------------------------------------------#
## Author = 'Vivek Trivedi  (Genpact Limited)'                                      ##
## Version = '1.0.0'                                                                ##
## Date = 6-Apr-2018                                                                ##
#------------------------------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description: Core Databases for all environments in Primary and Backup Regions.
Parameters:
    Prefix:
        Description: Prefix Name
        Default: pvai
        Type: String
    Region: 
        Description: AWS Region
        Default: N-Virginia(us-east-1)
        Type: String
        AllowedValues: 
           - N-Virginia(us-east-1)
           - Ireland(eu-west-1)
        ConstraintDescription: Select the Region for creation.
    EnvType: 
        Description: Environment Type
        Default: VAL
        Type: String
        AllowedValues: 
           - DEV
           - ML
           - SIT
           - VAL
           - PROD
           - UT
           - PT
        ConstraintDescription: Select the Environment for Creation.
    Engine:
        Description: Select the DB Engine.
        Default: oracle-se2
        Type: String
        AllowedValues: 
           - oracle-ee
           - oracle-se2
        ConstraintDescription: Select the DB Engine.   
    DBInstanceType: 
        Description: Database Instance Type
        Default: db.m4.xlarge
        Type: String
    LicenseModel: 
        Description: Select the License Model
        Default: license-included
        Type: String
        AllowedValues:
           - bring-your-own-license
           - license-included
    BackupRetentionPeriod: 
        Description: Time to retain the DB Backups
        Default: 30
        Type: String
    MasterUsername: 
        Description: Master User Name for the DB.
        Default: pvai
        Type: String 
    MasterUserPassword: 
        Description: Master Password for the DB.
        Default: XXXXXXX
        Type: String
        NoEcho: 'true'
    AllocatedStorage:
        Description: Specify the storage in GB.
        Default: 100
        Type: String
    EngineVersion: 
        Description: Specify the Oracle Engine Version.
        Default: '12.1.0.2.v11'
        Type: String
    MajorVersionUpgrade: 
        Description: Major Version Upgrade for DB.
        Default: 'false'
        Type: String
        AllowedValues: 
           - true
           - false
    MinorVersionUpgrade: 
        Description: Minor Version Upgrade for the DB.
        Default: 'true'
        Type: String
        AllowedValues: 
           - true
           - false
    StorageType: 
        Description: Enter a valid Storage Type 
        Default: 'io1'
        Type: String
    DBSnapshot:
        Description: DB Snapshot to be used for creation 
        Default: ""
        Type: String
    RDSKmsKeyId:
        Description: KMS Key for RDS Encryption 
        Default: "0831aea2-7a2d-4e44-a248-242a070cbafc"
        Type: String
    MultiAZEnabled:
        Description: To enable MultiAZ deployment
        Default: 'true'
        Type: String
        AllowedValues: [ 'true', 'false' ]
    HostedZoneResource:
       Description: Private DNS
       Type: String
       Default: local.
Conditions: 
  GetDevNetworkValues: !And
        - !Equals [ !Ref EnvType, DEV ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  GetMLNetworkValues: !And
        - !Equals [ !Ref EnvType, ML ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  GetSITNetworkValues: !And
        - !Equals [ !Ref EnvType, SIT ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  GetValNetworkValues: !And
        - !Equals [ !Ref EnvType, VAL ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  GetProdNetworkValues: !And
        - !Equals [ !Ref EnvType, PROD ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]      
  GetValNetworkValuesIreland: !And
        - !Equals [ !Ref Region, Ireland(eu-west-1) ]
        - !Equals [ !Ref EnvType, VAL ]
  GetProdNetworkValuesIreland: !And
        - !Equals [ !Ref Region, Ireland(eu-west-1) ]
        - !Equals [ !Ref EnvType, PROD ]
  GetUTNetworkValues: !And
        - !Equals [ !Ref EnvType, UT ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  GetPTNetworkValues: !And
        - !Equals [ !Ref EnvType, PT ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
Resources:
  securitygroupRDS:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for RDS'
      VpcId: !If [GetValNetworkValues, !ImportValue vpc30A, !If [GetProdNetworkValues, !ImportValue vpc30A, !If [GetDevNetworkValues, !ImportValue vpc31A, !If [GetMLNetworkValues, !ImportValue vpc31A, !If [GetPTNetworkValues, !ImportValue vpc34A, !If [GetUTNetworkValues, !ImportValue vpc33A, !If [GetSITNetworkValues, !ImportValue vpc32A, !If [GetProdNetworkValuesIreland,!ImportValue vpc30B, !If [GetValNetworkValuesIreland, !ImportValue vpc30B, ""]]]]]]]]]
      Tags:
        - Key: Name
          Value: !If [GetValNetworkValues, 'pvai-val-rds-vpc30A', !If [GetProdNetworkValues, 'pvai-prod-rds-vpc30A', !If [GetDevNetworkValues, 'pvai-dev-rds-vpc31A', !If [GetMLNetworkValues, 'pvai-ml-rds-vpc31A', !If [GetPTNetworkValues, 'pvai-pt-rds-vpc34A', !If [GetUTNetworkValues, 'pvai-ut-rds-vpc33A', !If [GetSITNetworkValues, 'pvai-sit-rds-vpc32A', !If [GetProdNetworkValuesIreland,'pvai-prod-rds-vpc30B', !If [GetValNetworkValuesIreland, 'pvai-val-rds-vpc30B', ""]]]]]]]]]
          
  RDSingress1:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref securitygroupRDS
      IpProtocol: '-1'
      FromPort: '1521'
      ToPort: '1521'
      CidrIp: 10.0.0.0/8

  RDSegress1:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !Ref securitygroupRDS
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
      
  rdssubnetgroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Created from the RDS CFN Template
      SubnetIds:
        - !If [GetValNetworkValues, !ImportValue subnet35b0A, !If [GetProdNetworkValues, !ImportValue subnet36b0A, !If [GetDevNetworkValues, !ImportValue subnet35b1A, !If [GetMLNetworkValues, !ImportValue subnet36b1A, !If [GetPTNetworkValues, !ImportValue subnet34b4A, !If [GetUTNetworkValues, !ImportValue subnet34b3A, !If [GetSITNetworkValues, !ImportValue subnet34b2A, !If [GetProdNetworkValuesIreland,!ImportValue subnet36b0B, !If [GetValNetworkValuesIreland, !ImportValue subnet35b0B, ""]]]]]]]]]
        - !If [GetValNetworkValues, !ImportValue subnet39b0A, !If [GetProdNetworkValues, !ImportValue subnet310b0A, !If [GetDevNetworkValues, !ImportValue subnet39b1A, !If [GetMLNetworkValues, !ImportValue subnet310b1A, !If [GetPTNetworkValues, !ImportValue subnet36b4A, !If [GetUTNetworkValues, !ImportValue subnet36b3A, !If [GetSITNetworkValues, !ImportValue subnet36b2A, !If [GetProdNetworkValuesIreland,!ImportValue subnet310b0B, !If [GetValNetworkValuesIreland, !ImportValue subnet39b0B, ""]]]]]]]]]

  rds:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '100'
      AllowMajorVersionUpgrade: !Ref MajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref MinorVersionUpgrade
      CharacterSetName: UTF8
      DBInstanceClass: !Ref DBInstanceType
      Port: '1521'
      StorageType: !Ref StorageType
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      PreferredBackupWindow: '00:00-00:30'
      PreferredMaintenanceWindow: 'sun:01:00-sun:02:00'
      Iops: '1000'
      CopyTagsToSnapshot: 'true'
      DBInstanceIdentifier: !Sub DB${EnvType} 
      DBName: !Sub DB${EnvType}
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      LicenseModel: !Ref LicenseModel
      MultiAZ: !Ref MultiAZEnabled
      DBSubnetGroupName: !Ref rdssubnetgroup
      StorageEncrypted: 'true'
      KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${RDSKmsKeyId}"
      DBSnapshotIdentifier: !Ref DBSnapshot
      VPCSecurityGroups:
        - !Ref securitygroupRDS
      Tags:
        - Key: Environment
          Value: !Ref EnvType
  # Creating DNS record for the RDS Instance
  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneResource
      Comment: Private DNS for RDS Instance.
      RecordSets:
      - Name: !Sub "${Prefix}-${EnvType}-oracle-rds-01.${HostedZoneResource}" 
        Type: CNAME
        TTL: '60'
        ResourceRecords:
        - !GetAtt rds.Endpoint.Address