#------------------------------------------------------------------------------------#
## Copyright © Genpact 2018. All Rights Reserved.                                   ##
## Ltd trading as G in NYSE - Registered in US.                                     ##
## Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.  ##
#------------------------------------------------------------------------------------#
## Author = 'Pankaj Motwani  (Genpact Limited)'                                     ##
## Version = '1.0.0'                                                                ##
## Date = 6-Apr-2018                                                                ##
#------------------------------------------------------------------------------------#
#------------------------------------------------------------------------------------#
## modified_by = 'Sandeep Kumar  (Genpact Limited)'                                 ##
## ver = '1.0.1'                                                                    ##
## changes = "Environment specific dependencies removed and all resources           ##
##           created at account level only"                                         ##
## date = '1-Oct-2018'                                                              ##
#------------------------------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket Creation for Cloud Trail along with Bucket Policy.
Parameters:
    Region: 
        Description: AWS Region
        Default: "Primary"
        Type: String
        AllowedValues: 
           - Primary
           - Secondary
   # AWS Account Name to be entered
    AWSAccount: 
        Description: AWS Account for CloudTrail logs
        Default: product
        Type: String
   # Cloud Trail logs Expiration in Days
    ExpirationPeriod:
        Description: Expiration in Days
        Default: 60
        Type: Number
   # Transition to Glacier in Days
    TransitionPeriod:
        Description: Transiton to Galcier in Days
        Default: 30
        Type: Number
# Define the conditions to be used later during resource creation
Conditions:
   CreateBucketInSecondary: !Equals [ !Ref Region, Secondary ]
   CreateBucketInPrimary: !Equals [ !Ref Region, Primary ] 
# Resources tag   
Resources:
  CloudTrailAPIActivityPrimary:
    Type: 'AWS::S3::Bucket'
    Condition: CreateBucketInPrimary
    Properties:
      AccessControl: Private
      BucketName: !Sub pvai-${AWSAccount}-primary-cloudtrail
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !Sub arn:aws:iam::${AWS::AccountId}:role/S3RoleForReplication
        Rules:
         - Id: MyRule1
           Status: Enabled
           Prefix: ""
           Destination:
             Bucket: !Sub arn:aws:s3:::pvai-${AWSAccount}-secondary-cloudtrail
             StorageClass: STANDARD
      LifecycleConfiguration:
        Rules:
          - Id: Rule1
            Prefix: ''
            Status: Enabled
            ExpirationInDays: !Ref ExpirationPeriod
            Transitions:
              - TransitionInDays: !Ref TransitionPeriod
                StorageClass: Glacier
  CloudTrailAPIActivitySecondary:
    Type: 'AWS::S3::Bucket'
    Condition: CreateBucketInSecondary
    Properties:
      AccessControl: Private
      BucketName: !Sub pvai-${AWSAccount}-secondary-cloudtrail
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Rule1
            Prefix: ''
            Status: Enabled
            ExpirationInDays: !Ref ExpirationPeriod
            Transitions:
              - TransitionInDays: !Ref TransitionPeriod
                StorageClass: Glacier
  CloudTrailAPIActivityPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Condition: CreateBucketInPrimary
    Properties:
      Bucket: !If [ CreateBucketInSecondary, !Ref CloudTrailAPIActivitySecondary, !Ref CloudTrailAPIActivityPrimary ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Get Bucket ACL access for CloudTrail service
          - Sid: AWSCloudTrailAclCheck20180329
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CloudTrailAPIActivityPrimary
          # Allow Write permission to cloudtrail service
          - Sid: AWSCloudTrailPutPermission
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CloudTrailAPIActivityPrimary
                - /AWSLogs/
                - !Ref AWS::AccountId
                - /*
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
          # Deny Delete permissions for all resources
          - Sid: DenyDeleteAccess
            Effect: Deny
            Principal: "*"
            Action: 
            - s3:DeleteObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CloudTrailAPIActivityPrimary
                - '/*'
          # Deny Delete permissions for root account as well
          - Sid: DenyDeleteAccessForRoot
            Effect: Deny
            Principal:             
               AWS:
               - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: 
              - s3:DeleteObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CloudTrailAPIActivityPrimary
                - '/*'

Outputs:
  CloudTrailAPIActivity:
    Value: !If [ CreateBucketInSecondary, !Ref CloudTrailAPIActivitySecondary, !Ref CloudTrailAPIActivityPrimary ]
    Description: Exporting CloudTrailS3Bucket
    Export:
     Name: !Sub cloudtrail-s3-bucket