#------------------------------------------------------------------------------------#
## Copyright © Genpact 2018. All Rights Reserved.                                   ##
## Ltd trading as G in NYSE - Registered in US.                                     ##
## Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.  ##
#------------------------------------------------------------------------------------#
## Author = 'Vivek Trivedi (Genpact Limited)'                                       ##
## Version = '1.0.0'                                                                ##
## Date = 6-Apr-2018                                                                ##
#------------------------------------------------------------------------------------#s
AWSTemplateFormatVersion: 2010-09-09
Description: CORE InternetGateway Creation and IG-VPC Association 
Parameters:
    Region: 
        Description: AWS Region
        Default: N-Virginia(us-east-1)
        Type: String
        AllowedValues: 
           - N-Virginia(us-east-1)
           - Ireland(eu-west-1)
        ConstraintDescription: Select the Region for creation.
    EnvType: 
        Description: Environment Type
        Default: DEV/ML
        Type: String
        AllowedValues: 
           - DEV/ML
           - SIT
           - VAL/PROD
           - UserTraining
           - PerformanceTesting
        ConstraintDescription: Select the Environment for Creation.
Conditions: 
  CreateCondition1A: !And
        - !Equals [ !Ref EnvType, DEV/ML ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition2A: !And
        - !Equals [ !Ref EnvType, SIT ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition0A: !And
        - !Equals [ !Ref EnvType, VAL/PROD ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition0B: !And
        - !Equals [ !Ref Region, Ireland(eu-west-1) ]
        - !Equals [ !Ref EnvType, VAL/PROD ]
  CreateCondition3A: !And
        - !Equals [ !Ref EnvType, UserTraining ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition4A: !And
        - !Equals [ !Ref EnvType, PerformanceTesting ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
Resources:
  vpc2ig1A:
    Type: 'AWS::EC2::InternetGateway'
    Condition: CreateCondition1A
    Properties:
      Tags:
        - Key: Name
          Value: vpc2ig1A
          
  vpc2ig2A:
    Condition: CreateCondition2A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc2ig2A
          
  vpc2ig0A:
    Condition: CreateCondition0A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc2ig0A
          
  vpc2ig0B:
    Condition: CreateCondition0B
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc2ig0B
          
  vpc2ig3A:
    Condition: CreateCondition3A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc2ig3A
          
  vpc2ig4A:
    Condition: CreateCondition4A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc2ig4A
          
  vpc3ig1A:
    Condition: CreateCondition1A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc3ig1A
          
  vpc3ig2A:
    Condition: CreateCondition2A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc3ig2A
          
  vpc3ig0A:
    Condition: CreateCondition0A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc3ig0A
          
  vpc3ig0B:
    Condition: CreateCondition0B
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc3ig0B
          
  vpc3ig3A:
    Condition: CreateCondition3A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc3ig3A
          
  vpc3ig4A:
    Condition: CreateCondition4A
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: vpc3ig4A
   
  attachvpc2ig1A:
    Condition: CreateCondition1A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc21A
      InternetGatewayId: !Ref vpc2ig1A 
 
  attachvpc2ig2A:
    Condition: CreateCondition2A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc22A
      InternetGatewayId: !Ref vpc2ig2A

  attachvpc2ig0A:
    Condition: CreateCondition0A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc20A
      InternetGatewayId: !Ref vpc2ig0A
      
  attachvpc2ig0B:
    Condition: CreateCondition0B
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc20B
      InternetGatewayId: !Ref vpc2ig0B

  attachvpc2ig3A:
    Condition: CreateCondition3A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc23A
      InternetGatewayId: !Ref vpc2ig3A

  attachvpc2ig4A:
    Condition: CreateCondition4A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc24A
      InternetGatewayId: !Ref vpc2ig4A

  attachvpc3ig1A:
    Condition: CreateCondition1A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc31A
      InternetGatewayId: !Ref vpc3ig1A
  
  attachvpc3ig2A:
    Condition: CreateCondition2A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc32A
      InternetGatewayId: !Ref vpc3ig2A
  
  attachvpc3ig0A:
    Condition: CreateCondition0A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc30A
      InternetGatewayId: !Ref vpc3ig0A
  
  attachvpc3ig0B:
    Condition: CreateCondition0B
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc30B
      InternetGatewayId: !Ref vpc3ig0B
  
  attachvpc3ig3A:
    Condition: CreateCondition3A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc33A
      InternetGatewayId: !Ref vpc3ig3A
  
  attachvpc3ig4A:
    Condition: CreateCondition4A
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !ImportValue vpc34A
      InternetGatewayId: !Ref vpc3ig4A
Outputs:
  vpc2ig1A:
    Condition: CreateCondition1A
    Value: !Ref vpc2ig1A 
    Export:
      Name: vpc2ig1A
  vpc2ig2A:
    Condition: CreateCondition2A
    Value: !Ref vpc2ig2A 
    Export:
      Name: vpc2ig2A
  vpc2ig0A:
    Condition: CreateCondition0A
    Value: !Ref vpc2ig0A 
    Export:
      Name: vpc2ig0A
  vpc2ig0B:
    Condition: CreateCondition0B
    Value: !Ref vpc2ig0B 
    Export:
      Name: vpc2ig0B
  vpc2ig3A:
    Condition: CreateCondition3A
    Value: !Ref vpc2ig3A 
    Export:
      Name: vpc2ig3A
  vpc2ig4A:
    Condition: CreateCondition4A
    Value: !Ref vpc2ig4A 
    Export:
      Name: vpc2ig4A
  vpc3ig1A:
    Condition: CreateCondition1A
    Value: !Ref vpc3ig1A 
    Export:
      Name: vpc3ig1A
  vpc3ig2A:
    Condition: CreateCondition2A
    Value: !Ref vpc3ig2A 
    Export:
      Name: vpc3ig2A
  vpc3ig0A:
    Condition: CreateCondition0A
    Value: !Ref vpc3ig0A 
    Export:
      Name: vpc3ig0A
  vpc3ig0B:
    Condition: CreateCondition0B
    Value: !Ref vpc3ig0B 
    Export:
      Name: vpc3ig0B
  vpc3ig3A:
    Condition: CreateCondition3A
    Value: !Ref vpc3ig3A 
    Export:
      Name: vpc3ig3A
  vpc3ig4A:
    Condition: CreateCondition4A
    Value: !Ref vpc3ig4A 
    Export:
      Name: vpc3ig4A     
  attachvpc2ig1A:
    Condition: CreateCondition1A
    Value: !Ref attachvpc2ig1A 
    Export:
      Name: attachvpc2ig1A
  attachvpc2ig2A:
    Condition: CreateCondition2A
    Value: !Ref attachvpc2ig2A 
    Export:
      Name: attachvpc2ig2A
  attachvpc2ig0A:
    Condition: CreateCondition0A
    Value: !Ref attachvpc2ig0A  
    Export:
      Name: attachvpc2ig0A
  attachvpc2ig0B:
    Condition: CreateCondition0B
    Value: !Ref attachvpc2ig0B 
    Export:
      Name: attachvpc2ig0B
  attachvpc2ig3A:
    Condition: CreateCondition3A
    Value: !Ref attachvpc2ig3A  
    Export:
      Name: attachvpc2ig3A
  attachvpc2ig4A:
    Condition: CreateCondition4A
    Value: !Ref attachvpc2ig4A 
    Export:
      Name: attachvpc2ig4A
  attachvpc3ig1A:
    Condition: CreateCondition1A
    Value: !Ref attachvpc3ig1A 
    Export:
      Name: attachvpc3ig1A
  attachvpc3ig2A:
    Condition: CreateCondition2A
    Value: !Ref attachvpc3ig2A 
    Export:
      Name: attachvpc3ig2A
  attachvpc3ig0A:
    Condition: CreateCondition0A
    Value: !Ref attachvpc3ig0A 
    Export:
      Name: attachvpc3ig0A
  attachvpc3ig0B:
    Condition: CreateCondition0B  
    Value: !Ref attachvpc3ig0B 
    Export:
      Name: attachvpc3ig0B
  attachvpc3ig3A:
    Condition: CreateCondition3A
    Value: !Ref attachvpc3ig3A  
    Export:
      Name: attachvpc3ig3A
  attachvpc3ig4A:
    Condition: CreateCondition4A
    Value: !Ref attachvpc3ig4A  
    Export:
      Name: attachvpc3ig4A