#------------------------------------------------------------------------------------#
## Copyright © Genpact 2018. All Rights Reserved.                                   ##
## Ltd trading as G in NYSE - Registered in US.                                     ##
## Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.  ##
#------------------------------------------------------------------------------------#
## Author = 'Vivek Trivedi (Genpact Limited)'                                       ##
## Version = '1.0.0'                                                                ##
## Date = 27-Jul-2018                                                                ##
#------------------------------------------------------------------------------------#

AWSTemplateFormatVersion: 2010-09-09
Description: CORE Subnet and RouteTable Association
Parameters:
    Region: 
        Description: AWS Region
        Default: N-Virginia(us-east-1)
        Type: String
        AllowedValues: 
           - N-Virginia(us-east-1)
           - Ireland(eu-west-1)
        ConstraintDescription: Select the Region for creation.
    EnvType: 
        Description: Environment Type
        Default: DEV/ML
        Type: String
        AllowedValues: 
           - DEV/ML
           - SIT
           - VAL/PROD
           - UserTraining
           - PerformanceTesting
        ConstraintDescription: Select the Environment for Creation.
Conditions: 
  CreateCondition1A: !And
        - !Equals [ !Ref EnvType, DEV/ML ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition2A: !And
        - !Equals [ !Ref EnvType, SIT ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition0A: !And
        - !Equals [ !Ref EnvType, VAL/PROD ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition0B: !And
        - !Equals [ !Ref Region, Ireland(eu-west-1) ]
        - !Equals [ !Ref EnvType, VAL/PROD ]
  CreateCondition3A: !And
        - !Equals [ !Ref EnvType, UserTraining ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
  CreateCondition4A: !And
        - !Equals [ !Ref EnvType, PerformanceTesting ]
        - !Equals [ !Ref Region, N-Virginia(us-east-1) ]
Resources:
  subnet27b1A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition1A
    Properties:
      CidrBlock: 10.10.12.0/24
      AvailabilityZone: us-east-1b
      VpcId: !ImportValue vpc21A
      Tags:
        - Key: Name
          Value: subnet-27b-1A
  subnet28b1A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition1A
    Properties:
      CidrBlock: 10.10.14.0/24
      AvailabilityZone: us-east-1c
      VpcId: !ImportValue vpc21A
      Tags:
        - Key: Name
          Value: subnet-28b-1A
  subnet25b2A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition2A
    Properties:
      CidrBlock: 10.50.8.0/24
      AvailabilityZone: us-east-1b
      VpcId: !ImportValue vpc22A
      Tags:
        - Key: Name
          Value: subnet-25b-2A
  subnet26b2A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition2A
    Properties:
      CidrBlock: 10.50.10.0/24
      AvailabilityZone: us-east-1c
      VpcId: !ImportValue vpc22A
      Tags:
        - Key: Name
          Value: subnet-26b-2A
  subnet27b0A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition0A
    Properties:
      CidrBlock: 10.20.12.0/24
      AvailabilityZone: us-east-1b
      VpcId: !ImportValue vpc20A
      Tags:
        - Key: Name
          Value: subnet-27b-0A
  subnet28b0A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition0A
    Properties:
      CidrBlock: 10.20.14.0/24
      AvailabilityZone: us-east-1c
      VpcId: !ImportValue vpc20A
      Tags:
        - Key: Name
          Value: subnet-28b-0A  		  
  subnet27b0B:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition0B
    Properties:
      CidrBlock: 10.21.12.0/24
      AvailabilityZone: eu-west-1b
      VpcId: !ImportValue vpc20B
      Tags:
        - Key: Name
          Value: subnet-27b-0B
  subnet28b0B:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition0B
    Properties:
      CidrBlock: 10.21.14.0/24
      AvailabilityZone: eu-west-1c
      VpcId: !ImportValue vpc20B
      Tags:
        - Key: Name
          Value: subnet-28b-0B	
  subnet25b3A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition3A
    Properties:
      CidrBlock: 10.30.8.0/24
      AvailabilityZone: us-east-1b
      VpcId: !ImportValue vpc23A
      Tags:
        - Key: Name
          Value: subnet-25b-3A
  subnet26b3A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition3A
    Properties:
      CidrBlock: 10.30.10.0/24
      AvailabilityZone: us-east-1c
      VpcId: !ImportValue vpc23A
      Tags:
        - Key: Name
          Value: subnet-26b-3A
  subnet25b4A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition4A
    Properties:
      CidrBlock: 10.60.8.0/24
      AvailabilityZone: us-east-1b
      VpcId: !ImportValue vpc24A
      Tags:
        - Key: Name
          Value: subnet-25b-4A
  subnet26b4A:
    Type: 'AWS::EC2::Subnet'
    Condition: CreateCondition4A
    Properties:
      CidrBlock: 10.60.10.0/24
      AvailabilityZone: us-east-1c
      VpcId: !ImportValue vpc24A
      Tags:
        - Key: Name
          Value: subnet-26b-4A
Outputs:
  subnet27b1A:
    Condition: CreateCondition1A
    Description: Reporting Subnet-1 - DEV/ML
    Value: !Ref subnet27b1A 
    Export:
      Name: subnet27b1A
  subnet28b1A:
    Condition: CreateCondition1A
    Description: Reporting Subnet-2 - DEV/ML
    Value: !Ref subnet28b1A 
    Export:
      Name: subnet28b1A
  subnet25b2A:
    Condition: CreateCondition2A
    Description: Reporting Subnet-1 - SIT
    Value: !Ref subnet25b2A 
    Export:
      Name: subnet25b2A
  subnet26b2A:
    Condition: CreateCondition2A
    Description: Reporting Subnet-2 - SIT
    Value: !Ref subnet26b2A 
    Export:
      Name: subnet26b2A
  subnet27b0A:
    Condition: CreateCondition0A
    Description: Reporting Subnet-1 - VAL/PROD - Virginia
    Value: !Ref subnet27b0A 
    Export:
      Name: subnet27b0A
  subnet28b0A:
    Condition: CreateCondition0A
    Description: Reporting Subnet-2 - VAL/PROD - Virginia
    Value: !Ref subnet28b0A  
    Export:
      Name: subnet28b0A
  subnet27b0B:
    Condition: CreateCondition0B
    Description: Reporting Subnet-1 - VAL/PROD - Ireland
    Value: !Ref subnet27b0B 
    Export:
      Name: subnet27b0B
  subnet28b0B:
    Condition: CreateCondition0B
    Description: Reporting Subnet-2 - VAL/PROD - Ireland
    Value: !Ref subnet28b0B 
    Export:
      Name: subnet28b0B
  subnet25b3A:
    Condition: CreateCondition3A
    Description: Reporting Subnet-1 - UT
    Value: !Ref subnet25b3A 
    Export:
      Name: subnet25b3A
  subnet26b3A:
    Condition: CreateCondition3A
    Description: Reporting Subnet-2 - UT
    Value: !Ref subnet26b3A  
    Export:
      Name: subnet26b3A
  subnet25b4A:
    Condition: CreateCondition4A
    Description: Reporting Subnet-1 - PT
    Value: !Ref subnet25b4A 
    Export:
      Name: subnet25b4A 
  subnet26b4A:
    Condition: CreateCondition4A
    Description: Reporting Subnet-2 - PT
    Value: !Ref subnet26b4A 
    Export:
      Name: subnet26b4A