---
# -------------------------------------------------------------------------------------------------
#
#     Copyright © Genpact 2018. All Rights Reserved.
#     Ltd trading as G in NYSE - Registered in US.
#     Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.
#
# -------------------------------------------------------------------------------------------------
## author = 'Atul Kumar (Genpact Limited)'
## ver = '1.0.0'
## date = 22-Feb-2019
# -------------------------------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function for deleting DB

Parameters:
  AccountName:
      Description: AWS Account Name
      Default: verification
      Type: String
  Region:
      Type: String
      Default: ap-northeast-1
      Description: Region where you want to create the Lambda function
  EnvType:
      Description: Environment Type
      Default: prod
      Type: String
      AllowedValues: [ dev, ut, pt, val ]
      ConstraintDescription: Select the Environment for Creation.
# Pre-requisite for Lambda function to create an IAM role
# which will have access on CloudWatch logs and RDS service
  ExecutionRole:
      Description: Role for Lambda function
      Default: lambda-rds-testing
      Type: String
  LambdaS3Bucket:
      Description: S3 Bucket for Lambda Function
      Default: "pvai-verification-lambda-functions"
      Type: String
  MemorySize:
      Description: Memory Size for Lambda function
      Default: 128
      Type: String
  TimeOut:
      Description: TimeOut for Lambda function (in seconds)
      Default: 300
      Type: String
  PythonPackage:
      Description: Python function as a package with all dependencies
      Default: "dbdeletion.zip"
      Type: String
  DatabaseID:
      Description: Database Identifier
      Default: "dbprod"
      Type: String
Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
          S3Bucket: !Ref LambdaS3Bucket
          S3Key: !Ref PythonPackage
        Description: "Delete running RDS Instance"
        Environment:
          Variables:
            REGION: !Ref Region
            DB_ID: !Ref DatabaseID            
        FunctionName: !Sub "${AccountName}-${EnvType}-delete-db"
        Handler: "dbdeletion.lambda_handler"
        MemorySize: !Ref MemorySize
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ExecutionRole}"
        Runtime: "python2.7"
        Timeout: !Ref TimeOut
        Tags:
          - Key: Name
            Value: !Sub "${EnvType}-Delete-DB"
          - Key: Account
            Value: !Ref AccountName
          - Key: Environment
            Value: !Ref EnvType

Outputs:
  LambdaArn:
    Value: !GetAtt "LambdaFunction.Arn"