---
# -------------------------------------------------------------------------------------------------
#
#     Copyright © Genpact 2018. All Rights Reserved.
#     Ltd trading as G in NYSE - Registered in US.
#     Registered Office - Canon's Court, 22 Victoria Street HAMILTON, HM 12, Bermuda.
#
# -------------------------------------------------------------------------------------------------
## author = 'Sandeep Kumar (Genpact Limited)'
## ver = '1.0.0'
## date = 30-Jan-2019
# -------------------------------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function to create AWS ES Repository

Parameters:
  AccountName:
      Description: AWS Account Name
      Default: product
      Type: String
  Region:
      Type: String
      Default: us-east-1
      AllowedValues:
      - "us-east-1"
      - "eu-west-1"
      Description: Please specify the region where you want to create your Lambda function
  EnvType:
      Description: Environment name
      Type: String
      Default: dev
      AllowedValues: ["dev", "pt", "ml", "val", "prod", "sit", "ut"]
# Pre-requiste for Lambda function to create an IAM role
# which will have access on ES and EC2 service
  ExecutionRole:
      Description: Role for Lambda function
      Default: lambda-es-cleaner
      Type: String
  LambdaS3Bucket:
      Description: S3 Bucket for Lambda Function
      Default: "pvai-devops-lambda-functions"
      Type: String
  SnapshotBucket:
      Description: S3 Bucket for ElasticSearch Repository
      Default: "pvai-dev-es-s3-repository"
      Type: String
  MemorySize:
      Description: Memory Size for Lambda function
      Default: 128
      Type: String 
  SecurityGroup:
      Description: Security Group ID associated with the Lambda function
      Default: "sg-8b991cc0"
      Type: String
  TimeOut:
      Description: TimeOut for Lambda function (in seconds)
      Default: 30
      Type: String
  PythonPackage:
      Description: Python function as a package with all dependencies
      Default: "register-es-repo.zip"
      Type: String
  ESDomainEndPoint:
      Description: "ES Domain EndPoint ex: https://<es domain>.<region>.es.amazonaws.com/"
      Default: "https://vpc-pvai-dev-log-7a3lpeaagptadbekuvnogzrqj4.us-east-1.es.amazonaws.com/"
      Type: String
  SnapshotRole:
      Description: Role ARN for ES Repository
      Default: "pvai-es-s3-repository"
      Type: String
  RepoSuffix:
      Description: Snapshot Repo Suffix
      Default: "es-snapshot-repo"
      Type: String
Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
          S3Bucket: !Ref LambdaS3Bucket
          S3Key: !Ref PythonPackage
        Description: "register es repo for environment specific domain"
        Environment:
          Variables:
            SNAPSHOT_BUCKET: !Ref SnapshotBucket
            REGION: !Ref Region
            ES_HOST: !Ref ESDomainEndPoint
            ROLE_ARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/${SnapshotRole}"
            REPO_NAME: !Sub ${EnvType}-${RepoSuffix} 
        FunctionName: !Sub "${EnvType}-register-es-repo"
        Handler: "register-repo.lambda_handler"
        MemorySize: !Ref MemorySize
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ExecutionRole}"
        Runtime: "python2.7"
        Timeout: !Ref TimeOut
        VpcConfig:
           "SecurityGroupIds": [ !Ref SecurityGroup ]
           "SubnetIds": [ !ImportValue subnet13bA , !ImportValue subnet14bA ]
        Tags:
          - Key: Name
            Value: !Sub "${EnvType}-es-repo"
          - Key: Environment
            Value: !Ref EnvType
          - Key: Account
            Value: !Ref AccountName

Outputs:
  LambdaArn:
    Value: !GetAtt "LambdaFunction.Arn"